services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: piga
      POSTGRES_PASSWORD: piga
      POSTGRES_DB: piga_padel
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
